spring:
  application:
    name: keycloak-app


  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9090/realms/triwal-realm-dev
          jwk-set-uri: http://localhost:9090/realms/triwal-realm-dev/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: triwal-app
      main-attr: preferred_username



logging:
  level:
    root: debug